package org.firstinspires.ftc.teamcode.pedro;

import com.pedropathing.algorithm.Foresight;
import com.pedropathing.algorithm.ForesightConfig;
import com.pedropathing.controllers.Controller;
import com.pedropathing.follower.Follower;
import com.pedropathing.math.Matrix;
import com.pedropathing.math.Vector2D;
import com.pedropathing.revhub.drivetrains.Mecanum;
import com.pedropathing.revhub.drivetrains.MecanumConfig;
import com.pedropathing.revhub.localizers.PinpointConfig;
import com.pedropathing.revhub.localizers.PinpointLocalizer;
import com.qualcomm.hardware.gobilda.GoBildaPinpointDriver;
import com.qualcomm.robotcore.hardware.DcMotorSimple;
import com.qualcomm.robotcore.hardware.HardwareMap;

import org.firstinspires.ftc.robotcore.external.navigation.DistanceUnit;

/**
 * Pedro Pathing 3.x configuration for team 24620.
 *
 * !! MEASURED ON THE TEST PLATFORM, NOT THE COMPETITION ROBOT. Re-run AutoTune on the real
 * robot; the structure carries over, the numbers do not.
 *
 * Do not hand-edit the blocks below. Run **AutoTune** (the "Tuning" OpMode, then open the
 * robot-hosted page) and paste what it generates. It measures pod directions and offsets
 * instead of making you read telemetry and guess, which is where this team lost hours in
 * August.
 */
public class Constants {

    // ==== Generated by AutoTune on the test chassis, 2026-10-03. ====
    // Do not hand-edit. Re-run the matching procedure and paste its output instead.

    // 1. Mecanum Drivetrain
    public static MecanumConfig drivetrainConfig = new MecanumConfig(c -> {
        c.frontLeftName.set("FrontLeft");
        c.frontRightName.set("FrontRight");
        c.backLeftName.set("BackLeft");
        c.backRightName.set("BackRight");
        c.frontLeftDirection.set(DcMotorSimple.Direction.REVERSE);
        c.frontRightDirection.set(DcMotorSimple.Direction.FORWARD);
        c.backLeftDirection.set(DcMotorSimple.Direction.REVERSE);
        c.backRightDirection.set(DcMotorSimple.Direction.FORWARD);
    });

    // 2. Pinpoint Localizer
    // !! yPodDirection and the SIGN of yPodOffset are hand-corrected. AutoTune output
    // FORWARD / -6.579, but REVERSED was proven on this unchanged robot in August (Direction
    // Test: driving left made y DECREASE under FORWARD). Under FORWARD the strafe axis reads
    // backwards: the hold test drifted when pushed and the pod test failed. Flipping the
    // direction flips the offset's sign, so the measured magnitude 6.579 is kept.
    // Likely cause: front/back confusion in AutoTune's "push" step. FRONT = POD END.
    public static PinpointConfig localizerConfig = new PinpointConfig(c -> {
        c.name.set("odo");
        c.podType.set(GoBildaPinpointDriver.GoBildaOdometryPods.goBILDA_4_BAR_POD);
        c.xPodOffset.set(1.7173301516555428);
        c.yPodOffset.set(6.579001719557395);
        c.xPodDirection.set(GoBildaPinpointDriver.EncoderDirection.FORWARD);
        c.yPodDirection.set(GoBildaPinpointDriver.EncoderDirection.REVERSED);
        c.globalDistanceUnit.set(DistanceUnit.INCH);
        c.offsetUnits.set(DistanceUnit.INCH);
    });

    // 3. Foresight
    public static ForesightConfig foresightConfig = new ForesightConfig(c -> {
        Controller primaryTranslationalForward = Controller.proportional(0.1602827488652105);
        Controller secondaryTranslationalForward = Controller.proportional(0.05922019287176751);
        Controller primaryTranslationalLateral = Controller.proportional(0.27014910700287814);
        Controller secondaryTranslationalLateral = Controller.proportional(0.09981287652047903);

        c.forwardTranslational.set(Controller.piecewise(secondaryTranslationalForward).put(2.5, primaryTranslationalForward));
        c.strafeTranslational.set(Controller.piecewise(secondaryTranslationalLateral).put(2.5, primaryTranslationalLateral));

        c.coast.set(Controller.proportionalFeedforward(0.016756968499221116));
        c.brake.set(Controller.proportionalFeedforward(0.014243423224337949));

        c.headingFeedback.set(Controller.proportional(2.7165062381843836));
        c.headingBrakeCoefficients.set(Vector2D.cartesian(0.0434582242978929, 0.00527635041204258));

        c.linearBrakeCoefficients.set(Matrix.diag(0.05898580505629485, 0.04579467007287008));
        c.quadraticBrakeCoefficients.set(Matrix.diag(0.0015997730801820898, 0.0018673662171516255));

        c.maxAchievableForwardVelocity.set(59.977473693025615);
        c.maxAchievableStrafeVelocity.set(46.03064173719523);
        // Positive in 3.x. The 2.x zero-power accelerations were negative (-26.5 / -29.8),
        // and carrying one over is what made the Tests procedure throw a config error.
        c.naturalForwardDeceleration.set(35.558059234391145);
        c.naturalStrafeDeceleration.set(56.17406431077795);
    });

    /** Argument order is (Localizer, Drivetrain, Algorithm) — not what the Quickstart comment says. */
    public static Follower create(HardwareMap hardwareMap) {
        return new Follower(
                new PinpointLocalizer(hardwareMap, localizerConfig),
                new Mecanum(hardwareMap, drivetrainConfig),
                new Foresight(foresightConfig));
    }
}
